Repository itmo-is-dev/ASAP, pull requests merged in 2023-03, with the labels that each got.

#65 fix: update github endpoint
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Github/Commands/UpdateSubjectCourseOrganizations.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Github/SubjectCourses/UpdateSubjectCourseOrganizationsHandler.cs
  Source/Playground/ITMO.Dev.ASAP.DataImport/Program.cs
  Source/Presentation/ITMO.Dev.ASAP.Controllers/GithubManagementController.cs
Labels: kind:fix

#66 Dev
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Github/Commands/UpdateSubjectCourseOrganizations.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Github/SubjectCourses/UpdateSubjectCourseOrganizationsHandler.cs
  Source/Playground/ITMO.Dev.ASAP.DataImport/Program.cs
  Source/Presentation/ITMO.Dev.ASAP.Controllers/GithubManagementController.cs
Labels: kind:fix

#68 Dev
  Source/Application/ITMO.Dev.ASAP.Application.GithubWorkflow/OrganizationManagement/SubjectCourseGithubOrganizationManager.cs
Labels: kind:fix

#69 Maksise4ka/47 create branch by mentor
  Source/Application/ITMO.Dev.ASAP.Application.Abstractions/ITMO.Dev.ASAP.Application.Abstractions.csproj
  Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Identity/ICurrentUser.cs
  Source/Application/ITMO.Dev.ASAP.Application.Common/Exceptions/ApplicationException.cs
  Source/Application/ITMO.Dev.ASAP.Application.Common/Exceptions/UserHasNotAccessException.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Study/SubjectCourses/Queries/GetSubjectCourses.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCourseByIdHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesBySubjectIdHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCoursesHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Subjects/GetSubjectByIdHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Subjects/GetSubjectsHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application/ITMO.Dev.ASAP.Application.csproj
  Source/Application/ITMO.Dev.ASAP.Application/Users/AdminUser.cs
  Source/Application/ITMO.Dev.ASAP.Application/Users/AnonymousUser.cs
  Source/Application/ITMO.Dev.ASAP.Application/Users/CurrentUserProxy.cs
  Source/Application/ITMO.Dev.ASAP.Application/Users/MentorUser.cs
  Source/Application/ITMO.Dev.ASAP.Application/Users/ModeratorUser.cs
  Source/Presentation/ITMO.Dev.ASAP.Controllers/SubjectController.cs
  Source/Presentation/ITMO.Dev.ASAP.Controllers/SubjectCourseController.cs
  Source/Tests/ITMO.Dev.ASAP.Tests.Handlers/ITMO.Dev.ASAP.Tests.Handlers.csproj
  Source/Tests/ITMO.Dev.ASAP.Tests.Handlers/Study/Subjects/GetSubjectTest.cs
Labels: type:task

#76 Eminbegin/44 Account Management
  Docker/docker-compose.yml
  Source/Application/ITMO.Dev.ASAP.Application.Common/Exceptions/UpdatePasswordFailedException.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Identity/Commands/CreateAdmin.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Identity/Commands/Register.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Identity/Commands/UpdatePassword.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Identity/Commands/UpdateUsername.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Identity/Queries/GetPasswordOptions.cs
  Source/Application/ITMO.Dev.ASAP.Application.Dto/Identity/PasswordOptionsDto.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Identity/CreateAdminHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Identity/GetPasswordOptionsHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Identity/UpdatePasswordHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Identity/UpdateUsernameHandler.cs
  Source/Domain/ITMO.Dev.ASAP.Common/Exceptions/UpdateUsernameFailedException.cs
  Source/Infrastructure/ITMO.Dev.ASAP.Identity/Extensions/ServiceCollectionExtensions.cs
  Source/Infrastructure/ITMO.Dev.ASAP.Mapping/Mappings/PasswordOptionsMapping.cs
  Source/Presentation/ITMO.Dev.ASAP.Controllers/IdentityController.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Abstractions/Models/Identity/UpdatePasswordRequest.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Abstractions/Models/Identity/UpdateUsernameRequest.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/IIdentityClient.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/Implementations/IdentityClient.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi/Helpers/SeedingHelper.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi/appsettings.json
Labels: type:task

#81 closes #42: added create user frontend
  Docker/.env
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Github/Commands/UpdateSubjectCourseMentorTeam.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Github/Commands/UpdateSubjectCourseOrganization.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Students/Commands/TransferStudent.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Tools/PaginationConfiguration.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Users/Queries/GetUserIdentityInfos.cs
  Source/Application/ITMO.Dev.ASAP.Application.Dto/Querying/UserQueryParameter.cs
  Source/Application/ITMO.Dev.ASAP.Application.Dto/Users/UserCourseRole.cs
  Source/Application/ITMO.Dev.ASAP.Application.Dto/Users/UserIdentityInfoDto.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Extensions/ServiceCollectionExtensions.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Identity/UpdateUsernameHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Users/GitUserIdentityInfosHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application/Extensions/ServiceCollectionExtensions.cs
  Source/Application/ITMO.Dev.ASAP.Application/Queries/Users/UserGithubQueryLink.cs
  Source/Application/ITMO.Dev.ASAP.Application/Queries/Users/UserIsuQueryLink.cs
  Source/Application/ITMO.Dev.ASAP.Application/Queries/Users/UserNameQueryLink.cs
  Source/Application/ITMO.Dev.ASAP.Application/Users/AnonymousUser.cs
  Source/Directory.Packages.props
  Source/ITMO.Dev.ASAP.sln
  Source/Playground/ITMO.Dev.ASAP.Playground.Github/Extensions/ServiceCollectionExtensions.cs
  Source/Playground/ITMO.Dev.ASAP.Playground.Google/PlaygroundServices.cs
  Source/Presentation/ITMO.Dev.ASAP.Controllers/UserController.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Abstractions/Models/Users/GetUserIdentityInfosResponse.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/IUserClient.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/Implementations/UserClient.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi/Extensions/ServiceCollectionExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi/Program.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi/appsettings.json
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Fields/TextField.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Groups/GroupQueryComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Groups/StudyGroupComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Query/QueryComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Query/QueryComponent.razor.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Students/StudentQueryComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Users/CreateUserAccoutModal.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Users/UsersPagePaginationComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Extensions/StudentDtoExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Extensions/UserDtoExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/ITMO.Dev.ASAP.WebUI.AdminPanel.csproj
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Identity/IIdentityManager.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Identity/LocalStorageIdentityManager.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Study/SubjectsView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Users/UsersView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Shared/NavMenu.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Tools/EqualityComparerFactory.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/_Imports.razor
Labels: type:task

#82 close #48
  Source/Directory.Packages.props
  Source/Playground/ITMO.Dev.ASAP.DataImport/IdentityProvider.cs
  Source/Playground/ITMO.Dev.ASAP.DataImport/Program.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/Extensions/ServiceCollectionExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/Identity/AuthorizationMessageHandlerDecorator.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/Identity/IIdentityProvider.cs
  Source/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/Identity/ITokenProvider.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/App.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/IAuthorizationLoader.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/ICurrentUser.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/IPrincipalConsumer.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/IPrincipalService.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/ITokenConsumer.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/Implementations/CurrentUser.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/Implementations/LocalStorageAuthorizationLoader.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/Implementations/LocalStorageTokenConsumer.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/Implementations/PrincipalService.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/Implementations/PrincipalTokenConsumer.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/Implementations/StateProviderPrincipalConsumer.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Authorization/Implementations/TokenProviderConsumer.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Groups/StudyGroupComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/SubjectCourse/SubjectCourseComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/SubjectCourse/SubjectCourseHeaderComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/SubjectCourseAssociations/SubjectCourseGithubAssociationComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Users/CreateUserAccoutModal.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/ExceptionHandling/SafeExecutor.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Extensions/CurrentUserExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Extensions/IdentityManagerExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Extensions/ServiceCollectionExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Extensions/ServiceScopeExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/ITMO.Dev.ASAP.WebUI.AdminPanel.csproj
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Identity/IIdentityManager.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Identity/IIdentityService.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Identity/IdentityService.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Identity/IdentityStateProvider.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Identity/LocalStorageIdentityManager.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Navigation/INavigationConsumer.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Navigation/INavigationService.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Navigation/Implementations/NavigationService.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Global.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Groups/StudyGroups.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Identity/Login.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Identity/Logout.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Students/Students.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Study/SubjectView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Study/SubjectsView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Users/UsersView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Program.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/SafeExecution/SafeExecutionBuilder.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Shared/MainLayout.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Shared/NavMenu.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Tools/Constants.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/wwwroot/sample-data/weather.json
Labels: type:task, area:ui

#83 fix: exception handling
  Source/Presentation/ITMO.Dev.ASAP.WebApi/Helpers/SeedingHelper.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Students/Students.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Users/UsersView.razor
Labels: kind:fix
