Repository itmo-is-dev/ASAP, pull requests merged in 2023-04, with the labels that each got.

#88 Fix wrong branch message
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Github/Assignments/GetGitHubAssignmentHandler.cs
Labels: kind:fix, area:github

#89 refactor: study ui
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Assignments/AssignmentInfoComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Assignments/AssignmentsComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Groups/StudyGroupInfoComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/SubjectCourse/SubjectCourseGroupsComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Subjects/CreateSubjectModal.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Extensions/ServiceCollectionExtensions.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/ITMO.Dev.ASAP.WebUI.AdminPanel.csproj
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Components/SubjectCourseListComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Components/SubjectListComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Layouts/SubjectCourseListLayout.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Layouts/SubjectListLayout.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Pages/SubjectCoursePage.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Pages/SubjectPage.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Pages/SubjectsPage.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Providers/ISubjectCourseProvider.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Providers/ISubjectProvider.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Providers/SubjectCourseProvider.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Providers/SubjectProvider.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Identity/Login.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Study/SubjectView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Study/SubjectsView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Shared/Layouts/MainLayout.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Shared/NavMenu.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/wwwroot/css/app.css
Labels: kind:refactoring, area:ui

#90 fix: ui spacing
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/SubjectCourse/AssociationsComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Components/SubjectCourseListComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Layouts/SubjectCourseListLayout.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Layouts/SubjectListLayout.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Pages/SubjectCoursePage.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Pages/SubjectPage.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Markup/StudyNavigation/Pages/SubjectsPage.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Study/SubjectView.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/wwwroot/css/app.css
Labels: kind:fix, area:ui

#91 feat: add Update Group Assignment Deadline Test
  Source/Tests/ITMO.Dev.ASAP.Tests.Handlers/Study/GroupAssignments/UpdateGroupAssignmentDeadlineTest.cs
Labels: type:task, area:tests

#71 DianaNeumann/58 Queue SignalR Backend
  Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Google/Notifications/SubjectCourseGroupQueueUpdateNotification.cs
  Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Google/Notifications/SubjectCourseGroupQueueUpdatedNotification.cs
  Source/Application/ITMO.Dev.ASAP.Application.Abstractions/ITMO.Dev.ASAP.Application.Abstractions.csproj
  Source/Application/ITMO.Dev.ASAP.Application.Abstractions/Queue/IQueueUpdateService.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/ITMO.Dev.ASAP.Application.Contracts.csproj
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Study/Queues/Notifications/QueueUpdated.cs
  Source/Application/ITMO.Dev.ASAP.Application.Contracts/Study/Queues/Queries/GetSubmmissionsQueue.cs
  Source/Application/ITMO.Dev.ASAP.Application.Google/ITMO.Dev.ASAP.Application.Google.csproj
  Source/Application/ITMO.Dev.ASAP.Application.Google/Workers/GoogleTableUpdateWorker.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Google/SubjectCourseGroupQueueUpdateHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Google/SubjectCourseGroupQueueUpdatedHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Queues/GetSubmmissionsQueueHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Queues/UpdateQueueCacheNotificationHandler.cs
  Source/Application/ITMO.Dev.ASAP.Application/Extensions/ServiceCollectionExtensions.cs
  Source/Application/ITMO.Dev.ASAP.Application/Services/QueueUpdateService.cs
  Source/ITMO.Dev.ASAP.sln
  Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Abstractions/IQueueHubClient.cs
  Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Handlers/QueueUpdateNotificationHandler.cs
  Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Hubs/QueueHub.cs
  Source/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/ITMO.Dev.ASAP.Presentation.Rpc.csproj
Labels: type:task

#93 fix: migrations
  Source/Infrastructure/ITMO.Dev.ASAP.DataAccess/Migrations/20230322155354_ExtractedGithubIntegration.cs
Labels: kind:fix

#95 fix: frontend
  Source/Directory.Packages.props
  Source/Infrastructure/ITMO.Dev.ASAP.DataAccess/Migrations/20230322155354_ExtractedGithubIntegration.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/TopLevelModal.razor
Labels: kind:fix, area:ui

#96 fix: added github info to GetSubjectCourseById
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Study/SubjectCourses/GetSubjectCourseByIdHandler.cs
Labels: kind:fix

#97 fix: frontend page scrolling
  Source/Application/ITMO.Dev.ASAP.Application.Handlers/Students/FindStudentsByQueryHandler.cs
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Groups/GroupQueryComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Components/Students/StudentTableComponent.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Groups/StudyGroups.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Students/Students.razor
  Source/Presentation/ITMO.Dev.ASAP.WebUI.AdminPanel/Pages/Users/UsersView.razor
Labels: kind:fix, area:ui

#99 fix: workflows
  .dockerignore
  .github/workflows/dotnet-build.yml
  .github/workflows/sonar-cloud.yml
  Docker/build.dockerfile
  ITMO.Dev.ASAP.sln
  src/ITMO.Dev.ASAP/ITMO.Dev.ASAP.csproj
Labels: kind:fix

#100 chore: workflow restart trigger
  .github/workflows/dotnet-build.yml
  .github/workflows/sonar-cloud.yml
  .github/workflows/start-prod.yml
  .github/workflows/start-test.yml
  ITMO.Dev.ASAP.sln
  src/ITMO.Dev.ASAP/Helpers/SeedingHelper.cs
Labels: kind:fix

#101 fix: deploy script path
  YaCloud/start.py
  src/ITMO.Dev.ASAP/Extensions/GoogleIntegrationServiceCollectionExtensions.cs
Labels: kind:fix

#102 fix: deploy
  Docker/build.dockerfile
  src/ITMO.Dev.ASAP/appsettings.json
Labels: kind:fix

#103 fix: deploy
  .github/workflows/start-test.yml
  Docker/build.dockerfile
Labels: kind:fix

#104 fix: deploy
  Docker/build.dockerfile
  src/ITMO.Dev.ASAP/appsettings.json
Labels: kind:fix

#105 fix: deploy
  .github/workflows/dotnet-build.yml
  .github/workflows/sonar-cloud.yml
  Docker/build.dockerfile
  YaCloud/start.py
  src/ITMO.Dev.ASAP/appsettings.json
Labels: kind:fix

#106 fix: deploy
  Docker/build.dockerfile
  src/ITMO.Dev.ASAP/appsettings.json
Labels: kind:fix

#108 fix: deploy
  .github/workflows/start-prod.yml
  .github/workflows/start-test.yml
  Docker/build.dockerfile
Labels: kind:fix

#109 feat: queue ui
  Directory.Packages.props
  src/ITMO.Dev.ASAP/Extensions/ServiceCollectionExtensions.cs
  src/ITMO.Dev.ASAP/Extensions/StartupExtensions.cs
  src/ITMO.Dev.ASAP/ITMO.Dev.ASAP.csproj
  src/core/Application/ITMO.Dev.ASAP.Application.Handlers/Study/Queues/GetSubmissionsQueueHandler.cs
  src/core/Presentation/ITMO.Dev.ASAP.Controllers/SubjectCourseController.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Abstractions/IQueueHubClient.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Extensions/ServiceCollectionExtensions.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Extensions/WebApplicationExtensions.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Handlers/QueueUpdateNotificationHandler.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Hubs/QueueHub.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/IAssemblyMarker.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/ITMO.Dev.ASAP.Presentation.Rpc.csproj
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Abstractions/ITMO.Dev.ASAP.WebApi.Abstractions.csproj
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Abstractions/Models/Queue/SubjectCourseQueueModel.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/ISubjectCourseClient.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/Implementations/SubjectCourseClient.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/Extensions/ServiceCollectionExtensions.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/HubClients/IHubClient.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/HubClients/IHubClientProvider.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/HubClients/IHubConnectionCreatable.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/HubClients/IQueueHubClient.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/HubClients/Implementations/HubClientProvider.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/HubClients/Implementations/StubQueueHubClient.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ITMO.Dev.ASAP.WebApi.Sdk.csproj
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/ITMO.Dev.ASAP.WebUI.Markup.csproj
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/Layouts/SubjectCourseListLayout.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/Layouts/SubjectListLayout.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/StudyNavigation/Pages/SubjectCoursePage.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Assignments/AssignmentComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Assignments/AssignmentInfoComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Assignments/AssignmentsComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Assignments/AssignmentsTabComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Groups/GroupsTabComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Groups/SubjectCourseGroupsComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Queue/SubmissionQueueComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Queue/SubmissionQueueItemComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/Queue/SubmissionQueueTabComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/SubjectCourseBreadcrumb.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/SubjectCourseComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/SubjectCourseGroupsComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/SubjectCourseListComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/SubjectCourseQueuesComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/SubjectCoursePage.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/SubjectCoursePage.razor.cs
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourseGroups/Components/AddSubjectCourseGroupModal.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/Subjects/Components/SubjectListComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/Subjects/SubjectPage.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/Subjects/SubjectsPage.razor
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Webhooks/Extensions/AppBuilderExtensions.cs
Labels: type:task, area:ui

#112 refactor: added subject course buttons
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/AssociationsComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/ForceSyncGitHubMentors.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/ForceSyncGithubOrganization.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/ForceSyncGoogle.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/Components/SubjectCourseHeaderComponent.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/SubjectCoursePage.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/SubjectCoursePage.razor.cs
Labels: kind:refactoring, area:ui

#113 fix: added github controllers
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Webhooks/Extensions/ServiceCollectionExtensions.cs
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Webhooks/ITMO.Dev.ASAP.Github.Presentation.Webhooks.csproj
Labels: kind:fix, area:github

#114 fix: github notifications
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Webhooks/Notifiers/ActionNotifier.cs
Labels: kind:fix, area:github

#115 chore: added webhook logging
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Webhooks/Processing/AsapWebhookEventProcessor.cs
Labels: area:github

#116 fix: github issue comment
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Webhooks/Notifiers/ActionNotifier.cs
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Webhooks/Notifiers/EventNotifierProxy.cs
Labels: kind:fix, area:github

#128 Fix/signalr authorization
  src/core/Application/ITMO.Dev.ASAP.Application.Abstractions/Identity/AsapIdentityRoleNames.cs
  src/core/Application/ITMO.Dev.ASAP.Application.Google/Dummy/Services/DummySubjectCourseTableService.cs
  src/core/Application/ITMO.Dev.ASAP.Application.Google/Dummy/Sheets/DummyLabsSheet.cs
  src/core/Application/ITMO.Dev.ASAP.Application.Google/Dummy/Sheets/DummyPointsSheet.cs
  src/core/Application/ITMO.Dev.ASAP.Application.Google/Dummy/Sheets/DummyQueueSheet.cs
  src/core/Application/ITMO.Dev.ASAP.Application.Google/Extensions/ServiceCollectionExtensions.cs
  src/core/Infrastructure/ITMO.Dev.ASAP.Identity/Extensions/ServiceCollectionExtensions.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/Hubs/QueueHub.cs
  src/core/Presentation/ITMO.Dev.ASAP.Presentation.Rpc/ITMO.Dev.ASAP.Presentation.Rpc.csproj
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/SubjectCourse/SubjectCoursePage.razor.cs
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/Subjects/SubjectPage.razor
  src/frontend/ITMO.Dev.ASAP.WebUI.Markup/Subjects/SubjectsPage.razor
  src/github/Presentation/ITMO.Dev.ASAP.Github.Presentation.Controllers/SubjectCourseController.cs
Labels: kind:fix

#130 fix: controller authorization
  src/core/Presentation/ITMO.Dev.ASAP.Controllers/AssignmentsController.cs
  src/core/Presentation/ITMO.Dev.ASAP.Controllers/StudyGroupController.cs
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/Implementations/StudyGroupClient.cs
Labels: kind:fix

#131 fix: study group sdk
  src/core/Presentation/ITMO.Dev.ASAP.WebApi.Sdk/ControllerClients/Implementations/StudyGroupClient.cs
Labels: kind:fix

#134 fix: github submission date
  src/github/ITMO.Dev.ASAP.Github.Domain/Submissions/GithubSubmission.cs
Labels: kind:fix, area:github

#135 fix: submission code generation
  src/core/Application/ITMO.Dev.ASAP.Application/Submissions/Workflows/SubmissionWorkflowBase.cs
Labels: kind:fix, area:core
